#
# Copyright (c) 2017-2018 Bitprim Inc.
#
# This file is part of Bitprim.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

build: off

branches:
  only:
    - master


skip_branch_with_pr: true

platform:
  - x64
  
configuration:
- Release

environment:

    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017


install:
  - git submodule init
  - git submodule update --remote
  - cinst docfx

build_script:
  - docfx

on_success:
  - git clone "https://%GIT_ACCESS_TOKEN%@github.com/bitprim/bitprim.github.io.git"
  - git config --global user.email "ci@kth.cash"
  - git config --global user.name "bitprim-ci"
  - cd _site
  - xcopy *.* C:\projects\bitprim-docs\bitprim.github.io\docs\ /s /e /y
  - cd ../bitprim.github.io
  - git add .
  - git commit -m "Updated documentation site"
  - git push 
  
test: off
