# Copyright (c) 2016-2020 Knuth Project developers.
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.


build: off

branches:
  only:
    - master


skip_branch_with_pr: true

platform:
  - x64
  
configuration:
- Release

environment:

    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017


install:
  - git submodule init
  - git submodule update --remote
  - cinst docfx

build_script:
  - docfx

on_success:
  - git clone "https://%GIT_ACCESS_TOKEN%@github.com/bitprim/k-nuth.github.io.git"
  - git config --global user.email "ci@kth.cash"
  - git config --global user.name "kth-ci"
  - cd _site
  - xcopy *.* C:\projects\bitprim-docs\k-nuth.github.io\docs\ /s /e /y
  - cd ../k-nuth.github.io
  - git add .
  - git commit -m "Updated documentation site"
  - git push 
  
test: off
